import { useState, useEffect } from 'react'
import dog1 from '../assets/dog1.png'
import dog2 from '../assets/dog2.png'
import dog3 from '../assets/dog3.png'
import dog4 from '../assets/dog4.png'
import dog5 from '../assets/dog5.png'
import dog6 from '../assets/dog6.png'
import dog7 from '../assets/dog7.png'
import dog8 from '../assets/dog8.png'
import dog10 from '../assets/dog10.png'
import dog11 from '../assets/dog11.png'
import dog12 from '../assets/dog12.png'

export type BarneyPose = 'celebrate' | 'happy' | 'neutral' | 'sad'

// dog9 (ATTACK/BARK) is omitted — aggressive snarling pose is off-tone for a friendly tutor
const FRIENDLY_DOGS = [dog1, dog2, dog3, dog4, dog5, dog6, dog7, dog8, dog10, dog11, dog12]

// Specific sprite per mood (dog5 JUMP, dog6 PLAY BOW, dog1 IDLE, dog8 SLEEP)
const POSE_DOG: Record<BarneyPose, string> = {
  celebrate: dog5,
  happy: dog6,
  neutral: dog1,
  sad: dog8,
}

interface BarnyProps {
  message?: string
  size?: 'small' | 'medium' | 'large'
  pose?: BarneyPose
  wordIdx?: number
}

const SIZE_PX: Record<string, number> = {
  small: 80,
  medium: 120,
  large: 180,
}

const RANDOM_QUIPS = [
  '¡Woof! Did you know "perro" means dog? That\'s me! 🐾',
  'Every word you learn is a treat for Barny! 🦴',
  'Sit. Stay. Study Spanish. Good human! 🐾',
  '¡Guau guau! That\'s Spanish for woof woof! 🐕',
  'Barny believes in you. Now get revising! 🐾',
  'Did you know dogs are called "perros" in Spanish? Very important. 🐕',
  'The more you practice, the more tail wags you get! 🐾',
  '¡Vamos! Let\'s go! Barny is ready when you are! 🏃',
  'Consistency is key — even Barny does the same walk every day! 🐾',
  'In Spanish, a good boy is "un buen chico." Barny is muy buen chico. 🐕',
  '¡Ánimo! You\'ve got this! Barny has never failed a sniff test. 🐾',
  'Small steps every day = big results. Barny learned to sit eventually. 🐕',
  'Fun fact: Barny\'s favourite Spanish word is "queso." It means cheese. 🧀',
  'Barny tip: say the Spanish words OUT LOUD. Woof loudly! 🔊',
  '¡Buenos días! Or if it\'s night — ¡Buenas noches! Barny covers all hours. 🐾',
  'You\'re here, which means you\'re already winning. Fetch! 🎾',
  'Barny\'s dream: visiting Spain. The smell. The food. The perros. 🇪🇸',
  '¡Excelente! You just thought about learning Spanish. First step done! 🐾',
  'In Spanish, "amigo" means friend. Barny is your amigo. 🐕',
  'Barny has been known to bork in both English AND Spanish. Bilingual king. 🐾',
  'If Barny can learn "sit," "stay," and "fetch," you can learn Spanish. ¡Fácil! 🐕',
  '"La vida es bella" — life is beautiful! Especially with Barny in it. 🐾',
  'Barny\'s studying too. He\'s on lesson one of "stop eating shoes." 🐕',
  '¿Cómo estás? That means "how are you?" Barny hopes you\'re doing great! 🐾',
  'Mistakes are just treats on the path to fluency. Nom nom. 🦴',
  'Barny rating: this study session will be a solid 10/10 wags. 🐾',
  '"Mañana" means tomorrow — but don\'t put studying off until mañana! 🐕',
  'Did someone say "vocabulario"? That\'s Barny\'s FAVOURITE word. 🐾',
  'Every correct answer makes Barny do a little spin. Get spinning! 🌀',
  'Barny fact: "cachorro" means puppy. Barny is eternally a cachorro at heart. 🐕',
  'You could be watching TV right now. But you\'re HERE. Legend. 🐾',
  '"Gracias" means thank you! Barny says gracias for studying today. 🐕',
  'Barny once barked in Spanish. It sounded like "guau." Absolutely nailed it. 🐾',
  'The secret to learning a language: repetition, repetition, repetición. 🦴',
  '"Bonito" means pretty. Like Barny\'s fur. Just saying. 🐕',
  '¡Mucho gusto! Nice to meet you — or nice to see you again! 🐾',
  'Barny tip: attach Spanish words to smells. Dog brain technique. 🐕',
  '"Tranquilo" means calm. Barny is the OPPOSITE of tranquilo. 🐾',
  'You are doing amazing sweetie. Barny said so. 🐕',
  '"Hoy" means today. TODAY is a great day to learn something new! 🐾',
  'Fun fact: there are 21 Spanish-speaking countries. That\'s 21x the sniffs! 🐕',
  'Barny\'s vocabulary is: woof, bark, bork, guau. He\'s working on it. 🐾',
  '"Lluvia" means rain. Barny hates it. But he loves that you\'re studying! 🐕',
  'Ole! Ole! Barny does not know what that means but he feels it deeply. 🐾',
  '"Fuerte" means strong. You are very fuerte for doing this. 🐕',
  'Barny\'s longest tail wag record: 4 minutes straight. Beat it with a streak! 🐾',
  '"Siempre" means always. Barny will ALWAYS be cheering you on. 🐕',
  '"Sueño" means dream OR sleep. Barny is living his sueño right now. 🐾',
  'Achievement unlocked: opened the app. Barny is proud. 🐕',
  '"Corazón" means heart. Barny has a very big corazón for learning humans. 🐾',

  // 200 more
  'Barny tried to order food in Spain once. He said "guau." They understood. 🐕',
  '"Feliz" means happy. Barny is VERY feliz right now. 🐾',
  'One word a day keeps the forgetting away. Barny heard that somewhere. 🦴',
  '¡Perfecto! Barny gives that a 12 out of 10 paws. 🐾',
  '"Dormir" means to sleep. Barny is an expert. PhD level. 🐕',
  'Barny once stared at a Spanish textbook for 20 minutes. Basically fluent. 🐾',
  '"Correr" means to run. Barny does this whenever he hears the word "bath." 🏃',
  'You are braver than you believe and smarter than Barny, which is saying something. 🐕',
  '"Agua" means water. Barny knocks his bowl over daily. Very refreshing. 🐾',
  'Barny\'s spirit animal is himself, but Spanish. 🇪🇸',
  '"Jugar" means to play. Barny endorses this activity 100%. 🎾',
  'If you get one wrong, that\'s fine. Barny fails to catch balls constantly. 🐕',
  '"Noche" means night. Barny is afraid of the dark. Don\'t tell anyone. 🌙',
  'The Spanish word for tail is "cola." Barny wags his cola at you. 🐾',
  '"Rápido" means fast. Barny can go rápido when there are squirrels involved. 🐕',
  'Every great linguist started knowing zero words. Barny started knowing zero words too. 🐾',
  '"Hambre" means hunger. This is Barny\'s permanent state. 🦴',
  'Barny would write flashcards but he has no thumbs. He relies on YOU. 🐕',
  '"Sol" means sun. Barny loves lying in the sun. Very important vocabulary. 🌞',
  '¡Increíble! That means incredible. Which is what you are. 🐾',
  '"Pelota" means ball. The most important word in any language. 🎾',
  'Barny once dreamed in Spanish. He woke up confused but impressed. 🐕',
  '"Listo" means ready OR clever. Barny hopes you are both. 🐾',
  'The hardest part of learning Spanish is starting. You already did that. Go Barny! 🦴',
  '"Pasear" means to go for a walk. Barny perked up just reading that. 🐕',
  'Barny trivia: "perrito caliente" is a hot dog. Barny is conflicted about this. 🌭',
  '"Jardín" means garden. Where Barny buries his vocabulary notes. 🐾',
  'Did you stretch before this study session? Barny always stretches. Look at him go. 🐕',
  '"Lluvia" means rain. Barny\'s nemesis. He will not be taking questions. 🌧️',
  'Barny has a 5-star Duolingo review in his head. He just can\'t type it. 🐾',
  '"Cama" means bed. Barny is thinking about his cama right now. 🛏️',
  'Proud of you! Barny does a bork of celebration in your honour. 🐕',
  '"Ventana" means window. Where Barny watches the world and judges it. 🐾',
  'You\'ve learned more Spanish than most people will this week. Barny verified. 🦴',
  '"Hueso" means bone. Barny just got very excited. Please continue. 🐕',
  'Barny believes language learning is a marathon, not a sprint. But also a sprint. Also fetch. 🐾',
  '"Caminar" means to walk. Barny\'s second favourite activity after eating. 🐕',
  'Barny tip: pretend you\'re a dog. Dogs learn through repetition and rewards. It works. 🐾',
  '"Abrir" means to open. Like opening your mind to Spanish! Barny is very wise. 🦴',
  'In Spain, dogs say "guau." In Mexico too. Barny is internationally relevant. 🐕',
  '"Frío" means cold. Barny shivers dramatically to illustrate. 🐾',
  'Your brain is like a sponge right now. Barny has eaten a sponge before. Different. 🐕',
  '"Calor" means heat. Barny pants enthusiastically to demonstrate. 🐾',
  'Barny thinks Spanish accents are very cool. The tildes! The upside-down marks! ¡Woof! 🦴',
  '"Juguete" means toy. Barny has opinions about which ones are best. Many opinions. 🐕',
  'Word of wisdom from Barny: if you don\'t know a word, just say "cosa." It means "thing." 🐾',
  '"Correa" means leash. Barny respects the leash. (He does not respect the leash.) 🐕',
  'Every word you learn lives rent-free in your brain. Make it a nice neighbourhood. 🐾',
  '"Fuera" means outside. Barny just sprinted to the door. 🦴',
  'Barny\'s favourite Spanish sentence: "¿Dónde está mi pelota?" Where is my ball? 🐕',
  '"Bonito" means pretty and "lindo" means cute. Barny is ambos. 🐾',
  'The trick to Spanish is confidence. Say it loud! Like a bork! BORK! 🐕',
  '"Descansar" means to rest. Barny is very qualified to teach this one. 🐾',
  'Fun fact: "can" in Spanish means "dog." Old Spanish. Barny finds this deeply meaningful. 🦴',
  '"Escuchar" means to listen. Barny\'s ears perk up at the word "walk." Expert listener. 🐕',
  'Barny considered a career in translation but couldn\'t figure out the keyboard. Here he is. 🐾',
  '"Ruidoso" means noisy. Also an accurate description of Barny at 6am. 🐕',
  '"Suave" means soft OR smooth. Barny\'s fur is muy suave, thank you. 🐾',
  '"Esperar" means to wait OR to hope. Barny waits AND hopes for treats simultaneously. 🦴',
  'Every mistake you make is data. Barny has a LOT of data about holes in gardens. 🐕',
  '"Tranquilo/a" means calm. Barny hears this a lot. Working on it. 🐾',
  '"Encantado/a" means delighted to meet you! Barny is always encantado. 🐕',
  'Barny philosophy: treat every wrong answer like a squirrel — chase it down next time. 🐾',
  '"Nuevo" means new. A new session, a new chance, a new Barny (same Barny). 🦴',
  '"Viejo" means old. Barny refuses to apply this word to himself. Eternally young. 🐕',
  '"Siesta" is the same in Spanish! A nap. Barny is a siesta professional. 🐾',
  'Barny once sat perfectly still for 3 minutes. Peak discipline. You can do this. 🐕',
  '"Hablar" means to talk. Barny talks (barks) constantly. He gets it. 🐾',
  '"Leer" means to read. Barny licks pages. Close enough. 🦴',
  '"Escribir" means to write. Barny paws at the screen. Very close. 🐕',
  '"Aprender" means to learn. This is literally what you\'re doing. Barny is THRILLED. 🐾',
  'The Spanish word "madrugada" means the hours between midnight and dawn. Very poetic. Very Barny. 🌙',
  '"Tarde" means afternoon OR late. Barny is never late. He arrives exactly when treats appear. 🐕',
  '"Temprano" means early. Barny is always temprano for breakfast. Always. 🐾',
  '"Semana" means week. Seven days. Seven chances to impress Barny. 🦴',
  '"Mes" means month. Barny marks months by how many walks he\'s had. A lot. 🐕',
  '"Año" means year. Barny is doing his best regardless of the year. 🐾',
  'Remember: "por favor" means please. Barny says it with his eyes constantly. 🐕',
  '"De nada" means you\'re welcome! Barny accepts your gratitude with a wag. 🐾',
  '"Lo siento" means I\'m sorry. Barny says this to the bins he knocks over. 🦴',
  '"No entiendo" means I don\'t understand. Barny says this to the bath. Every time. 🐕',
  '"¡Qué bueno!" means how great! Barny says this whenever food appears. 🐾',
  '"Despacio" means slowly. Barny eats the opposite of despacio. 🦴',
  'Barny once met a dog from Madrid. They got on great. Mostly sniffing. 🐕',
  '"Encontrar" means to find. Barny is excellent at finding smells. Transferable skill. 🐾',
  '"Perder" means to lose. Barny loses his ball daily and is fine. Resilience. 🐕',
  '"Ganar" means to win. Today you are GANAR-ing. Barny confirms. 🐾',
  '"Intentar" means to try. The fact that you\'re here means you\'re already intentando. 🦴',
  '"Olvidar" means to forget. Barny forgot where he buried his bone. Still searching. 🐕',
  '"Recordar" means to remember. This app is literally for that! Barny is very relevant! 🐾',
  '"Preguntar" means to ask. Barny asks for treats with his entire face. Works every time. 🦴',
  '"Contestar" means to answer. Barny always answers. The answer is usually "woof." 🐕',
  '"Entender" means to understand. Barny understands "walk," "treat," and "no" (he ignores no). 🐾',
  '"Empezar" means to begin. You already empezaste. Look at you go! 🐕',
  '"Terminar" means to finish. Barny finishes his food in 4 seconds flat. 🐾',
  'Barny tip: translate your thoughts into Spanish while on a walk. Barny does this. 🦴',
  '"Pensar" means to think. Barny is thinking about you right now. Proud thoughts. 🐕',
  '"Saber" means to know. Barny knows one thing: you are doing amazing. 🐾',
  '"Poder" means to be able to / can. YOU PODER THIS. Barny is sure. 🐕',
  '"Querer" means to want OR to love. Barny quieres treats AND you. Equally. 🐾',
  '"Tener" means to have. Barny has: one ball, one bed, and limitless love for Spanish learners. 🦴',
  '"Ir" means to go. ¡Vamos! Let\'s go! Barny is already at the door. 🐕',
  '"Venir" means to come. Barny always comes when called. (This is a lie.) 🐾',
  '"Poner" means to put. Barny puts things in his mouth. Educational. 🦴',
  '"Hacer" means to do or make. What are you going to hacer today? Barny votes: Spanish! 🐕',
  '"Ver" means to see. Barny sees a lot from the window. Mainly squirrels. 🐾',
  '"Dar" means to give. Please give Barny a treat. It\'s for motivation purposes. 🦴',
  'Barny once tried yoga. "Downward dog" felt very natural. 🐕',
  '"Saltar" means to jump. Barny jumps for: joy, food, and no reason at all. 🐾',
  '"Nadar" means to swim. Barny is... uncertain about swimming. The jury is out. 🐕',
  '"Cavar" means to dig. Barny is a cavar champion. Gold medal. 🐾',
  '"Olfatear" means to sniff. Barny\'s greatest talent. 10/10 technique, judges say. 🦴',
  'Barny has 300 million scent receptors. He is using them all to sense your progress. 🐕',
  '"Ladrar" means to bark. Barny does this. All the time. About everything. 🐾',
  '"Morder" means to bite. Barny ONLY does this to toys. Mostly. 🦴',
  '"Crecer" means to grow. Your Spanish is growing! Barny measured. 🐕',
  '"Cambiar" means to change. Every session changes your brain. Science! Barny! 🐾',
  '"Ayudar" means to help. Barny helps by existing. Very effective. 🦴',
  '"Llevar" means to carry or wear. Barny carries the weight of your motivation. 🐕',
  '"Traer" means to bring. Barny brings vibes. Good vibes. 🐾',
  '"Buscar" means to search or look for. Like how Barny looks for squirrels: obsessively. 🦴',
  '"Comprar" means to buy. Barny would buy treats. If he had money. Hint hint. 🐕',
  '"Comer" means to eat. Barny\'s primary skill. Expert level. Unbeatable. 🐾',
  '"Beber" means to drink. Barny drinks, then puts his wet beard on you. You\'re welcome. 🦴',
  'Your streak is like Barny\'s tail — keep it going! 🐕',
  '"Dormir" means to sleep. Barny maintains 16 hours per day. Aspirational. 🐾',
  '"Soñar" means to dream. Barny dreams about squirrels AND your Spanish success. 🦴',
  'Barny once went to a fiesta. He ate everything on the table. Legend. 🐕',
  '"Bailar" means to dance. Barny\'s tail is basically dancing right now. 🐾',
  '"Cantar" means to sing. Barny howls along to music. Artistic interpretation. 🦴',
  '"Esconder" means to hide. Where Barny goes when he hears the word "bath." 🐕',
  '"Compartir" means to share. Barny believes in sharing... mostly. 🐾',
  '"Necesitar" means to need. Barny needs: food, walks, and for you to succeed. 🦴',
  '"Deber" means to owe or should. You should (deber) learn a word today. Barny is firm. 🐕',
  '"Preferir" means to prefer. Barny prefers sunny walks and correct flashcard answers. 🐾',
  '"Parecer" means to seem or appear. It seems like you\'re doing great! Barny concurs. 🦴',
  '"Creer" means to believe. Barny believes in you more than he believes in the bath. 🐕',
  '"Sentir" means to feel. Barny feels everything very intensely. It\'s a gift. 🐾',
  '"Vivir" means to live. ¡Vive el español! Live the Spanish! Barny commands it. 🦴',
  '"Trabajar" means to work. Learning IS work! Hard, rewarding work. Barny respects it. 🐕',
  '"Descansar" means to rest. After this session: rest. You earned it. So did Barny. 🐾',
  '"Disfrutar" means to enjoy. ¡Disfruta tu sesión! Enjoy your session! 🦴',
  'Barny\'s top tip: visualise the word. Picture a perro when you say perro. (Picture Barny.) 🐕',
  '"Emocionado/a" means excited. Barny is emocionado EVERY single morning. Non-negotiable. 🐾',
  '"Nervioso/a" means nervous. It\'s okay to feel nervioso. Barny feels it before baths. 🦴',
  '"Cansado/a" means tired. It\'s okay to be cansado. Rest, then come back. Barny will wait. 🐕',
  '"Aburrido/a" means bored. You\'re NOT aburrido — you\'re here! With Barny! 🐾',
  '"Orgulloso/a" means proud. Barny is muy orgulloso of you. Always. 🦴',
  '"Asustado/a" means scared. Don\'t be asustado of hard words. Attack them like squirrels. 🐕',
  '"Confundido/a" means confused. It\'s okay. Even Barny gets confundido by the leash. 🐾',
  '"Sorprendido/a" means surprised. Barny gets surprised by his own reflection daily. 🦴',
  '"Tranquilo/a" means calm. Breathe. Take your time. Barny is in no rush. Well. Maybe a little. 🐕',
  '"Seguro/a" means sure OR safe. Barny makes you feel seguro. It\'s his job. 🐾',
  '"Listo/a" means ready. Are you listo? Barny has been listo since 6am. 🦴',
  '"Nuevo/a" means new. New vocabulary incoming! Barny is on the edge of his bed. 🐕',
  '"Simpático/a" means friendly. That\'s Barny. The most simpático dog in the game. 🐾',
  '"Inteligente" means intelligent. Barny believes this describes you exactly. 🦴',
  '"Valiente" means brave. You are valiente for learning something new. Barny salutes. 🐕',
  '"Paciente" means patient. Barny is patient. For about 10 seconds. Then he barks. 🐾',
  '"Curioso/a" means curious. Curiosity is how you learn. Sniff everything! 🦴',
  'Barny once confused "rojo" (red) and "ojo" (eye). He looked at things differently after. 🐕',
  '"Verde" means green. Barny rolls in green things. Not all of them pleasant. 🐾',
  '"Azul" means blue. The colour of the sky Barny stares at during walks. 🦴',
  '"Amarillo" means yellow. Barny has a yellow ball. It is his most prized possession. 🐕',
  '"Naranja" means orange (the colour AND the fruit). Barny is fascinated by oranges. 🐾',
  '"Blanco" means white. Barny has white paws (when they\'re clean, which is rarely). 🦴',
  '"Negro" means black. Barny\'s nose is negro. Perfect and important. 🐕',
  '"Gris" means grey. What Barny\'s muzzle is slowly becoming. Distinguished. 🐾',
  '"Grande" means big. Barny\'s energy is grande. Always. 🦴',
  '"Pequeño/a" means small. Barny was pequeño once. Very briefly. 🐕',
  '"Alto/a" means tall or high. Barny jumps alto for treats. Very alto. 🐾',
  '"Bajo/a" means short or low. Barny goes bajo when he wants belly rubs. 🦴',
  '"Largo/a" means long. Like the long list of words you\'re going to learn! 🐕',
  '"Corto/a" means short. This quip is corto. Unlike Barny\'s love for you. 🐾',
  '"Fácil" means easy. Some words ARE fácil. Celebrate those! 🦴',
  '"Difícil" means difficult. Some words are difícil. Still worth it. Barny struggled with "stay." 🐕',
  '"Importante" means important. Spanish is importante. Barny is importante. Both true. 🐾',
  '"Interesante" means interesting. Barny finds everything interesting. Sticks. Smells. You. 🦴',
  '"Divertido/a" means fun. Learning Spanish IS divertido. Barny insists. 🐕',
  '"Delicioso/a" means delicious. Barny considers most things delicioso. Including socks. 🐾',
  '"Increíble" means incredible. Your progress is increíble. Barny checked the data. 🦴',
  '"Perfecto/a" means perfect. No one is perfect — but you\'re perfectísimo to Barny. 🐕',
  '"Especial" means special. You are very especial. Barny has known since the start. 🐾',
  '"Famoso/a" means famous. One day you\'ll be famoso for your Spanish. Barny will say he knew you. 🦴',
  '"Favorito/a" means favourite. YOU are Barny\'s favourite. Don\'t tell the others. 🐕',
  '"Normal" is the same in Spanish! See, you already knew one! 🐾',
  '"Hospital" is the same too! Spanish has loads of English cognates. Sneaky easy! 🦴',
  '"Animal" is exactly the same in Spanish. Barny approves of this word. 🐕',
  '"Chocolate" is almost the same — "chocolate." Essential vocabulary, says Barny. 🐾',
  '"Hotel" is the same in Spanish. Barny has never stayed in one. Yet. 🦴',
  '"Universal" is the same in Spanish. See the pattern? "-al" words often cross over! 🐕',
  '"Natural" is the same in Spanish too! You\'re building vocab without even trying! 🐾',
  '"Tropical" — same in Spanish! Barny would like to visit somewhere tropical. 🦴',
  '"Central" — same in Spanish. You are central to Barny\'s daily motivation. 🐕',
  '"Actual" means CURRENT in Spanish, not real. Barny learned this the hard way. 🐾',
  'False friend alert: "embarazada" means pregnant, NOT embarrassed. Barny saves you. 🦴',
  'False friend: "sensible" in Spanish means sensitive, not sensible. Barny is both. 🐕',
  '"Éxito" means success, NOT exit. Your éxito in Spanish is Barny\'s whole goal. 🐾',
  '"Realizar" means to achieve or carry out, not to realise. Barny realised this recently. 🦴',
  'The verb "molestar" means to bother or annoy. Barny does not molestar. (He does.) 🐕',
  'Barny says: don\'t just memorise — USE the words. Talk to yourself. Talk to Barny! 🐾',
  'Write Spanish words on sticky notes. Put them everywhere. Like Barny puts muddy paws. 🦴',
  'Label things in your house in Spanish. Your bed is "la cama." Barny\'s is too. 🐕',
  'Change your phone language to Spanish for a week. Barny dares you. 🐾',
  'Listen to Spanish music! Barny recommends anything with a good beat for zoomies. 🦴',
  'Watch a show with Spanish subtitles. Barny watches from the sofa. Prime position. 🐕',
  'The more you immerse, the faster you learn. Barny immersed himself in a puddle once. 🐾',
  'Reading in Spanish, even slowly, rewires your brain. Barny\'s brain is very rewired. 🦴',
  'Think of a Spanish word right now. That\'s one more than you knew before Barny. 🐕',
  'Barny\'s final wisdom: show up. Every day. Even for five minutes. It all adds up. 🐾',
  '"¡Hasta luego!" — see you later! Barny will be here. Waiting. Always waiting. 🦴',

  // 250 more — numbers, days, months, family, food, body, house, animals, weather, places, jobs, clothing, grammar & study tips
  '"Uno" means one. Like the one ball Barny will never stop fetching. 🎾',
  '"Dos" means two. Two treats is Barny\'s preferred quantity. Minimum. 🦴',
  '"Tres" means three. Three walks a day? Barny would happily accept. 🐕',
  '"Cuatro" means four. Like Barny\'s four excellent paws. 🐾',
  '"Cinco" means five. High five! Or high cinco, in this case. 🐾',
  '"Seis" means six. Six o\'clock is when Barny demands breakfast. 🐕',
  '"Siete" means seven. Seven days a week, Barny believes in you. 🦴',
  '"Ocho" means eight. Barny can\'t count to ocho but he respects the number. 🐾',
  '"Nueve" means nine. Nine lives are for cats. Barny has infinite vibes. 🐕',
  '"Diez" means ten. Ten out of ten — that\'s your score today. Barny decided. 🐾',
  '"Once" means eleven (not "once"!). Sneaky little word. Barny was fooled too. 🦴',
  '"Doce" means twelve. Twelve treats would be a dream. Barny\'s dream. 🐕',
  '"Trece" means thirteen. Unlucky? Not for Barny. Every number is lucky. 🐾',
  '"Veinte" means twenty. Twenty words a week and you\'re flying. Barny calculated. 🦴',
  '"Cien" means one hundred. One hundred percent good boy: Barny. 🐕',
  '"Mil" means one thousand. A thousand tail wags for your effort today. 🐾',
  '"Primero" means first. The first lesson is the hardest. You did it. 🦴',
  '"Último" means last. Never the last time you\'ll impress Barny. 🐕',
  '"Medio" means half. Half a session still counts. Barny gives half-credit generously. 🐾',
  '"Número" means number. Barny\'s favourite número is the one on the treat bag. 🦴',
  '"Lunes" means Monday. Barny doesn\'t hate Mondays. Every day has walks. 🐕',
  '"Martes" means Tuesday. A great day to learn a verb. Barny says so. 🐾',
  '"Miércoles" means Wednesday. Hardest day to spell. Barny gave up and barked. 🦴',
  '"Jueves" means Thursday. Almost-Friday. Barny can sense the weekend coming. 🐕',
  '"Viernes" means Friday. ¡Por fin! Finally! Barny is ready to party (nap). 🐾',
  '"Sábado" means Saturday. Long walk day. Barny\'s favourite. 🦴',
  '"Domingo" means Sunday. Rest day. Barny is a professional rester. 🐕',
  '"Enero" means January. New year, new words. Barny made resolutions (broke them). 🐾',
  '"Febrero" means February. Short month, same big Barny love. 🦴',
  '"Marzo" means March. Spring sniffs incoming! Barny is excited. 🐕',
  '"Abril" means April. "En abril, aguas mil" — April showers! Barny hides. 🐾',
  '"Mayo" means May. Flowers bloom, Barny sneezes. Beautiful season. 🦴',
  '"Junio" means June. Summer\'s coming. Barny pre-pants in preparation. 🐕',
  '"Julio" means July. Hot month. Barny becomes a floor puddle. 🐾',
  '"Agosto" means August. Barny\'s nap quota peaks in agosto. 🦴',
  '"Septiembre" means September. Back-to-learning energy. Barny sharpened his focus. 🐕',
  '"Octubre" means October. Crunchy leaves = Barny\'s favourite walks. 🐾',
  '"Noviembre" means November. Cosy season begins. Barny claims the warmest spot. 🦴',
  '"Diciembre" means December. End of the year. Barny is proud of all you learned. 🐕',
  '"Familia" means family. You\'re part of Barny\'s familia now. 🐾',
  '"Madre" means mother. Barny loves his. She gives the best treats. 🦴',
  '"Padre" means father. In Mexico, "padre" can also mean "cool"! Barny is muy padre. 🐕',
  '"Hermano" means brother. Barny considers every dog his hermano. 🐾',
  '"Hermana" means sister. Barny\'s hermana stole his bed once. Forgiven. 🦴',
  '"Hijo" means son, "hija" daughter. Barny is everyone\'s hijo, really. 🐕',
  '"Abuelo/a" means grandfather/grandmother. They sneak Barny extra treats. 🐾',
  '"Tío/a" means uncle/aunt. Barny has many. All generous. 🦴',
  '"Primo/a" means cousin. Barny\'s primo is a poodle. Very fancy. 🐕',
  '"Bebé" means baby. Barny was a bebé once. Adorable. Chaos. 🐾',
  '"Comida" means food. Barny\'s number-one topic of conversation. 🍖',
  '"Pan" means bread. Barny would commit minor crimes for pan. 🥖',
  '"Leche" means milk. Barny prefers the puddle variety, but okay. 🥛',
  '"Huevo" means egg. Barny watches you cook huevos with great intensity. 🥚',
  '"Carne" means meat. Barny\'s eyes just lit up. Please continue. 🥩',
  '"Pollo" means chicken. Say "pollo" and Barny appears instantly. 🍗',
  '"Pescado" means fish (the kind you eat). Barny has strong feelings about it. 🐟',
  '"Fruta" means fruit. Barny likes fruta. Especially the dropped kind. 🍎',
  '"Manzana" means apple. Barny once stole a manzana. No regrets. 🍎',
  '"Plátano" means banana. Barny finds plátanos suspicious but edible. 🍌',
  '"Verdura" means vegetable. Barny eats them when no one\'s looking. 🥦',
  '"Arroz" means rice. Gets everywhere. Barny cleans the floor. Helpful. 🍚',
  '"Sopa" means soup. Too hot for Barny. He waits. Patiently. Sort of. 🍲',
  '"Café" means coffee. Barny doesn\'t drink it but loves the morning ritual. ☕',
  '"Azúcar" means sugar. Sweet, like your study streak. Barny approves. 🍬',
  '"Helado" means ice cream. Barny dreams of helado. The forbidden treat. 🍦',
  '"Galleta" means biscuit/cookie. Possibly Barny\'s favourite word ever. 🍪',
  '"Cena" means dinner. Barny\'s favourite meal. And lunch. And breakfast. 🍽️',
  '"Desayuno" means breakfast. Barny\'s alarm clock is his own stomach. 🥣',
  '"Cuerpo" means body. Barny\'s cuerpo is 90% wag. 🐾',
  '"Cabeza" means head. Barny tilts his cabeza when confused. Adorable. 🐕',
  '"Ojo" means eye. Barny\'s ojos can ask for anything and receive it. 👁️',
  '"Nariz" means nose. Barny\'s nariz is his superpower. 🐽',
  '"Boca" means mouth. Barny\'s boca holds things it really shouldn\'t. 🐾',
  '"Diente" means tooth. Barny shows his dientes when happy. Friendly! 🦷',
  '"Oreja" means ear. Barny\'s orejas hear the treat bag from a mile away. 👂',
  '"Mano" means hand. Barny gives you his "mano" (paw) for a treat. 🐾',
  '"Pie" means foot. Barny steps on yours lovingly. 🦶',
  '"Pierna" means leg. Barny leans his whole weight on your pierna. Love. 🐕',
  '"Pelo" means hair/fur. Barny\'s pelo is everywhere. A gift to your home. 🐾',
  '"Lengua" means tongue AND language! Barny\'s lengua does both jobs. 👅',
  '"Estómago" means stomach. Barny\'s rules his entire life. 🐕',
  '"Espalda" means back. Barny demands espalda scratches daily. 🐾',
  '"Casa" means house OR home. Barny makes any place a casa. 🏠',
  '"Puerta" means door. Barny stares at the puerta willing it to open. 🚪',
  '"Mesa" means table. Where Barny\'s eyes drift during dinner. 🪑',
  '"Silla" means chair. Barny is not allowed on the silla. (He is on the silla.) 🪑',
  '"Cocina" means kitchen. Barny\'s favourite room by a landslide. 🍳',
  '"Baño" means bathroom. The room Barny fears most. You know why. 🛁',
  '"Dormitorio" means bedroom. Where Barny "guards" you while sleeping. 🛏️',
  '"Suelo" means floor. Barny\'s preferred lounging surface. Cool and vast. 🐾',
  '"Pared" means wall. Barny once ran into a pared chasing a ball. Fine now. 🐕',
  '"Llave" means key. Barny knows keys mean leaving. He disapproves. 🔑',
  '"Reloj" means clock OR watch. Barny\'s internal reloj is set to "treat time." ⏰',
  '"Espejo" means mirror. Barny befriends the dog in the espejo daily. 🪞',
  '"Ventana" means window. Barny\'s personal television. Squirrel channel. 🪟',
  '"Gato" means cat. Barny respects cats. From a cautious distance. 🐈',
  '"Pájaro" means bird. Barny watches pájaros like nature documentaries. 🐦',
  '"Pez" means fish (alive). "Pescado" is the one you eat. Barny knows both. 🐠',
  '"Caballo" means horse. Barny saw a caballo once. Speechless. (For once.) 🐴',
  '"Vaca" means cow. Barny barked at a vaca. The vaca won. 🐄',
  '"Cerdo" means pig. Barny relates to the cerdo on a spiritual level. 🐖',
  '"Oveja" means sheep. Count ovejas to sleep. Barny counts treats. 🐑',
  '"Ratón" means mouse. Barny is "on it." (He is asleep.) 🐭',
  '"Conejo" means rabbit. Barny would love to discuss conejos. At length. 🐰',
  '"Oso" means bear. Barny thinks he\'s an oso. He is not. 🐻',
  '"León" means lion. Barny\'s spirit animal. In his dreams. 🦁',
  '"Tiempo" means weather OR time. Spanish is efficient. Barny appreciates it. ⛅',
  '"Nieve" means snow. Barny becomes a puppy again in the nieve. ❄️',
  '"Viento" means wind. Barny\'s ears flap majestically in the viento. 💨',
  '"Nube" means cloud. Barny watches nubes and contemplates treats. ☁️',
  '"Estrella" means star. Barny is a estrella. A very good one. ⭐',
  '"Luna" means moon. Barny howls at the luna. Artistic expression. 🌙',
  '"Mar" means sea. Barny is suspicious of the mar. So much water. 🌊',
  '"Río" means river. Barny drinks from rivers. "Free water," he says. 🏞️',
  '"Montaña" means mountain. Barny climbs them with surprising speed. ⛰️',
  '"Árbol" means tree. Barny\'s favourite outdoor furniture. 🌳',
  '"Flor" means flower. Barny sniffs every flor. Quality control. 🌸',
  '"Playa" means beach. Barny + playa = sand in everything, forever. 🏖️',
  '"Ciudad" means city. Barny finds cities loud but full of smells. 🏙️',
  '"Pueblo" means village/town. Barny prefers the quiet pueblo life. 🏘️',
  '"Calle" means street. Where Barny conducts his important sniffing. 🛣️',
  '"Tienda" means shop. Barny waits outside, looking tragic. 🏪',
  '"Mercado" means market. So many smells! Barny is overwhelmed (happy). 🧺',
  '"Escuela" means school. You\'re at Barny\'s escuela right now! 🏫',
  '"Parque" means park. Barny\'s holy ground. Sacred zoomie territory. 🌳',
  '"Banco" means bank OR bench. Barny prefers the bench meaning. 🪑',
  '"Restaurante" means restaurant. Barny has strong opinions about table scraps. 🍴',
  '"Aeropuerto" means airport. Barny does NOT enjoy the carrier. 🛫',
  '"Estación" means station. Trains! Barny finds them thrilling and terrifying. 🚉',
  '"Trabajo" means job/work. Barny\'s trabajo is being adorable. Full-time. 🐕',
  '"Médico/a" means doctor. Barny respects the vet. Mostly. 👨‍⚕️',
  '"Profesor/a" means teacher. Barny is YOUR profesor. Honoured. 🎓',
  '"Cocinero/a" means cook. Barny is the cocinero\'s loyal floor-cleaning assistant. 👨‍🍳',
  '"Policía" means police. Barny "helps" by barking at everything. 👮',
  '"Bombero/a" means firefighter. Barny is brave. Until the vacuum appears. 🚒',
  '"Cartero/a" means postal worker. Barny\'s sworn nemesis. 📬',
  '"Artista" means artist. Barny\'s art is muddy paw prints. Priceless. 🎨',
  '"Escritor/a" means writer. Barny would write but, again, no thumbs. ✍️',
  '"Ropa" means clothes. Barny doesn\'t wear ropa. He\'s perfect as is. 👕',
  '"Camisa" means shirt. Barny once wore a camisa. Mixed feelings. 👔',
  '"Pantalones" means trousers. Barny is glad he doesn\'t need pantalones. 👖',
  '"Zapatos" means shoes. Barny\'s mortal enemies AND favourite chew toys. 👟',
  '"Sombrero" means hat. Barny wore a sombrero once. Iconic. Brief. 👒',
  '"Abrigo" means coat. Barny has a built-in abrigo. Very convenient. 🧥',
  '"Calcetines" means socks. Barny collects them. A connoisseur. 🧦',
  '"Gafas" means glasses. Barny tried yours on. Distinguished look. 👓',
  '"Bufanda" means scarf. Barny stole one. It\'s his now. 🧣',
  '"Ahora" means now. The best time to learn? Ahora. Barny insists. ⏰',
  '"Después" means after/later. Treats después the lesson. Barny\'s rule. 🦴',
  '"Antes" means before. Stretch antes your study session. Barny does. 🐕',
  '"Nunca" means never. Barny would nunca skip a meal. Nunca. 🍖',
  '"A veces" means sometimes. Barny listens sometimes. A veces. 🐾',
  '"Pronto" means soon. You\'ll be fluent pronto. Barny can feel it. ✨',
  '"Todavía" means still/yet. Still learning? That\'s the whole point. 🦴',
  '"Qué" means what. "¿Qué?" is Barny\'s face when the food bag rustles. 🐕',
  '"Quién" means who. "¿Quién es un buen perro?" Barny. The answer is Barny. 🐾',
  '"Dónde" means where. "¿Dónde está la pelota?" Barny\'s eternal question. 🎾',
  '"Cuándo" means when. "¿Cuándo comemos?" — when do we eat? Asks Barny. Always. 🍖',
  '"Por qué" (two words) asks why; "porque" (one word) answers because! Barny: woah. 🦴',
  '"Cómo" means how. "¿Cómo estás?" Barny hopes the answer is "great!" 🐕',
  '"Cuánto" means how much/many. "¿Cuánto?" Barny\'s reaction to treat portions. 🐾',
  '"Cuál" means which. "¿Cuál pelota?" All of them, Barny. All the balls. 🎾',
  '"Hola" means hello. The first word everyone learns. Barny waves a paw. 🐾',
  '"Adiós" means goodbye. Barny hates adiós. He prefers "hasta pronto." 🐕',
  '"¿Qué tal?" means how\'s it going? Casual! Barny is muy casual. 🐾',
  '"Bienvenido/a" means welcome. Barny welcomes you to today\'s session! 🎉',
  '"Salud" means health — and what you say when someone sneezes! Barny says salud. 🤧',
  '"Felicidades" means congratulations! Barny throws confetti (sheds fur). 🎊',
  '"Buen provecho" means enjoy your meal. Barny says it. Then begs. 🍽️',
  '"Claro" means "of course!" Barny says claro to every walk proposal. 🐕',
  '"Vale" means "okay" in Spain. Barny picked this up instantly. ¡Vale! 🐾',
  '"Oye" means "hey, listen." Barny\'s ears say "oye" at every sound. 👂',
  '"Me llamo..." is how you say your name! "Me llamo Barny." Try yours. 🐕',
  '"Usar" means to use. Use your new words today! Barny commands it gently. 🐾',
  '"Pagar" means to pay. Barny pays in tail wags. Generous tipper. 🐕',
  '"Estudiar" means to study. THIS. This is what you\'re doing. ¡Olé! 📚',
  '"Enseñar" means to teach. Barny enseña Spanish and chaos. 🐾',
  '"Viajar" means to travel. Barny\'s travel dream: Spain. The smells! 🇪🇸',
  '"Llegar" means to arrive. You llegaste! You arrived! Session started! 🐕',
  '"Salir" means to leave/go out. The word that makes Barny sprint to the door. 🚪',
  '"Entrar" means to enter. Barny enters every room like he owns it. 🐾',
  '"Subir" means to go up. Barny sube the stairs at lightning speed. ⚡',
  '"Bajar" means to go down. Barny is suspicious of stairs going down. 🐕',
  '"Volver" means to return. Barny always wants you to volver soon. ❤️',
  '"Quedarse" means to stay. "Quédate." Stay. Barny\'s least favourite command. 🐾',
  '"Sentarse" means to sit. "¡Siéntate!" Barny knows this one. Sometimes. 🐕',
  '"Levantarse" means to get up. Barny se levanta instantly for food. ⚡',
  '"Lavar" means to wash. The dreaded prelude to "baño." Barny flees. 🛁',
  '"Limpio/a" means clean. A rare and temporary state for Barny. ✨',
  '"Sucio/a" means dirty. Barny\'s natural and preferred condition. 🐾',
  '"Lleno/a" means full. Barny\'s belly: frequently lleno. Goal achieved. 🦴',
  '"Vacío/a" means empty. Barny\'s food bowl: a tragedy. Vacío. 🐕',
  '"Caliente" means hot. Barny tests caliente food with his nose. Brave scientist. 🔥',
  '"Caro/a" means expensive. The treats Barny prefers are always caro. Typical. 💰',
  '"Barato/a" means cheap. Barny\'s love is free. The treats are not. 🐾',
  '"Mejor" means better. Every day you\'re getting mejor. Barny tracks it. 📈',
  '"Peor" means worse. Nothing\'s peor than an empty treat jar. Barny mourns. 🦴',
  '"Mismo/a" means same. Same time tomorrow? Barny will be here. 🐕',
  '"Otro/a" means other/another. "¿Otro treat?" Barny\'s eternal request. 🐾',
  '"Todo/a" means all/everything. Barny wants todo. All of it. Always. 🐕',
  '"Mucho/a" means a lot. Barny loves you mucho. Muchísimo, actually. ❤️',
  '"Poco/a" means a little. "Un poquito" — a tiny bit. Like Barny\'s patience. 🐾',
  '"Cada" means each/every. Cada día is a chance. Barny seizes cada one. 🦴',
  'Grammar tip: Spanish nouns have genders! "El perro" (m), "la casa" (f). Barny is very "el." 🐕',
  'Grammar tip: adjectives usually come AFTER the noun. "Perro grande" = big dog. 🐾',
  'Grammar tip: to make plurals, add -s or -es. "Perro" → "perros." More dogs! 🐕',
  'Grammar tip: "ser" and "estar" both mean "to be." Ser = permanent, estar = temporary. 🐾',
  'Grammar tip: upside-down ¿ and ¡ open questions and exclamations. ¡Qué útil! 🦴',
  'Grammar tip: "tú" is informal "you," "usted" is formal. Barny is strictly informal. 🐕',
  'Grammar tip: "ñ" is its own letter! "Año" (year) is very different from "ano." Mind the tilde! 🐾',
  'Grammar tip: "h" is always silent. "Hola" sounds like "ola." Barny\'s mind: blown. 🦴',
  'Grammar tip: "ll" often sounds like "y." "Llave" = "YAH-veh." Barny practised for hours. 🐕',
  'Grammar tip: "j" sounds like a throaty "h." "Jamón" = "ha-MON." Barny loves jamón. 🐾',
  'Grammar tip: roll your "r"! "Perro" needs a good roll. Barny growls his perfectly. 🦴',
  'Grammar tip: stress usually lands on the second-to-last syllable. Accents mark exceptions. 🐕',
  'Grammar tip: "gustar" works backwards. "Me gusta" = "it pleases me." Barny: "Me gustan los treats." 🐾',
  'Grammar tip: numbers don\'t change for gender, except "uno" → "una." "Una pelota." 🎾',
  'Grammar tip: "muy" means very, "mucho" means a lot. Barny is muy bueno AND eats mucho. 🦴',
  'Study tip: review right before sleep. Your brain files it overnight. Barny files dreams. 😴',
  'Study tip: teach someone else a word. Teach Barny! He\'s an excellent (silent) student. 🐕',
  'Study tip: little and often beats one big cram. Barny snacks; he doesn\'t feast. (Lie.) 🦴',
  'Study tip: connect words to feelings. "Feliz" = how Barny feels seeing you. 🐾',
  'Study tip: say words in silly voices. They stick better. Barny endorses silliness. 🐕',
  'Study tip: keep a tiny notebook of new words. Barny keeps a mental one of good smells. 📓',
  'Study tip: practise with real conversations — even with a dog! Barny\'s a great listener. 🦴',
  'Study tip: set a tiny daily goal. One word. Barny\'s daily goal: one (1) squirrel. 🐿️',
  'Study tip: celebrate small wins. Barny spins for every correct answer. Spin with him! 🌀',
  'Study tip: change your phone to Spanish for a week. Barny double-dog-dares you. 🐾',
  'Did you know? Spanish is spoken by over 500 million people. That\'s a lot of new friends! 🌍',
  'Did you know? Spanish is an official language in 20 countries. Barny wants to visit all 20. 🗺️',
  'Did you know? "¡Olé!" likely comes from Arabic. Spanish has many Arabic roots! Barny: woah. 🐾',
  'Did you know? In Spanish you don\'t "miss" someone — they "make a lack" to you. Poetic! 🦴',
  'Did you know? "Esposas" means both "wives" AND "handcuffs." Barny finds this hilarious. 🐕',
  'False friend: "ropa" means clothes, NOT rope. Barny double-checked. 🧦',
  'False friend: "carpeta" means folder, NOT carpet. Barny was very confused. 📁',
  'False friend: "librería" is a bookshop; "biblioteca" is a library. Barny mixed these up. 📚',
  'False friend: "constipado" means having a cold, NOT constipated. Barny dodged that one. 🤧',
  'False friend: "fábrica" means factory, NOT fabric. Barny learned the hard way. 🏭',
  'Barny\'s reminder: progress isn\'t always visible day to day. But it\'s happening. Trust it. 🐕',
  'Barny\'s reminder: comparing yourself to others is like a dog chasing its tail. Run YOUR race. 🐾',
  'Barny\'s reminder: you don\'t need to be perfect. You need to show up. You did. 🦴',
  'Barny\'s reminder: every fluent speaker was once exactly where you are now. Keep going. 🐕',
  'Barny\'s reminder: rest is part of learning too. Even Barny powers down to recharge. 😴',
  'Barny\'s reminder: a five-minute session still counts. Always counts. 🐾',
  'Barny\'s reminder: the words you "forget" aren\'t gone — they\'re just napping. Like Barny. 🦴',
  'Barny\'s reminder: confidence comes from doing, not waiting to feel ready. Bork bravely! 🐕',
  'Barny\'s reminder: one good question beats ten perfect answers. Stay curious. 🐾',
  'Barny\'s final-final wisdom: the best time to start was years ago. The second best is hoy. 🌳',
]

const ALL_DOGS = [dog1, dog2, dog3, dog4, dog5, dog6, dog7, dog8, dog10, dog11, dog12]

export function RotatingBarnyIcon({ size = 18 }: { size?: number }) {
  const [idx, setIdx] = useState(0)
  useEffect(() => {
    const id = setInterval(() => setIdx((i) => (i + 1) % ALL_DOGS.length), 100000)
    return () => clearInterval(id)
  }, [])
  return (
    <img
      src={ALL_DOGS[idx]}
      alt="Barny"
      style={{ width: size, height: size, objectFit: 'contain', display: 'inline-block', verticalAlign: 'middle', transform: 'scaleX(-1)' }}
    />
  )
}

export function Barny({ message, size = 'medium', pose, wordIdx = -1 }: BarnyProps) {
  const [randomSrc] = useState(() => FRIENDLY_DOGS[Math.floor(Math.random() * FRIENDLY_DOGS.length)])
  const [resolvedMessage] = useState(() => message ?? RANDOM_QUIPS[Math.floor(Math.random() * RANDOM_QUIPS.length)])
  const src = pose ? POSE_DOG[pose] : randomSrc
  const px = SIZE_PX[size]
  const cropH = Math.round(px * 0.8) // clip the baked-in sprite label at the bottom
  const bubbleFontSize = size === 'small' ? '12px' : '14px'
  const bubbleMaxWidth = size === 'large' ? '200px' : '160px'

  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: '12px', justifyContent: 'center' }}>
      <div style={{ width: px, height: cropH, flexShrink: 0, overflow: 'hidden' }}>
        <img
          src={src}
          alt="Barny the dog"
          width={px}
          style={{ width: px, height: 'auto', display: 'block', transform: 'scaleX(-1)' }}
        />
      </div>

      {resolvedMessage && (
        <div style={{ position: 'relative' }}>
          <div style={{
            position: 'absolute',
            left: '-9px',
            top: '50%',
            transform: 'translateY(-50%)',
            width: 0,
            height: 0,
            borderTop: '7px solid transparent',
            borderBottom: '7px solid transparent',
            borderRight: '9px solid var(--color-window-border)',
          }} />
          <div style={{
            background: 'var(--color-window-bg)',
            border: '2px solid var(--color-window-border)',
            padding: '6px 10px',
            fontSize: bubbleFontSize,
            fontFamily: 'var(--font-ui)',
            maxWidth: bubbleMaxWidth,
            lineHeight: 1.3,
            textAlign: 'left',
            boxShadow: '2px 2px 0 rgba(0,0,0,0.2)',
            borderRadius: '4px',
          }}>
            {wordIdx >= 0
              ? resolvedMessage.split(/\s+/).map((w, i) => (
                  <span key={i} style={{
                    textDecoration: i === wordIdx ? 'underline' : 'none',
                    textDecorationThickness: '2px',
                    transition: 'text-decoration 0.1s',
                  }}>{w}{' '}</span>
                ))
              : resolvedMessage
            }
          </div>
        </div>
      )}
    </div>
  )
}
