import { useState, useEffect } from 'react'
import dog1 from '../assets/dog1.png'
import dog2 from '../assets/dog2.png'
import dog3 from '../assets/dog3.png'
import dog4 from '../assets/dog4.png'
import dog5 from '../assets/dog5.png'
import dog6 from '../assets/dog6.png'
import dog7 from '../assets/dog7.png'
import dog8 from '../assets/dog8.png'
import dog10 from '../assets/dog10.png'
import dog11 from '../assets/dog11.png'
import dog12 from '../assets/dog12.png'

export type BarneyPose = 'celebrate' | 'happy' | 'neutral' | 'sad'

// dog9 (ATTACK/BARK) is omitted — aggressive snarling pose is off-tone for a friendly tutor
const FRIENDLY_DOGS = [dog1, dog2, dog3, dog4, dog5, dog6, dog7, dog8, dog10, dog11, dog12]

// Specific sprite per mood (dog5 JUMP, dog6 PLAY BOW, dog1 IDLE, dog8 SLEEP)
const POSE_DOG: Record<BarneyPose, string> = {
  celebrate: dog5,
  happy: dog6,
  neutral: dog1,
  sad: dog8,
}

interface BarnyProps {
  message?: string
  size?: 'small' | 'medium' | 'large'
  pose?: BarneyPose
  wordIdx?: number
}

const SIZE_PX: Record<string, number> = {
  small: 80,
  medium: 120,
  large: 180,
}

const RANDOM_QUIPS = [
  '¡Woof! Did you know "perro" means dog? That\'s me! 🐾',
  'Every word you learn is a treat for Barny! 🦴',
  'Sit. Stay. Study Spanish. Good human! 🐾',
  '¡Guau guau! That\'s Spanish for woof woof! 🐕',
  'Barny believes in you. Now get revising! 🐾',
  'Did you know dogs are called "perros" in Spanish? Very important. 🐕',
  'The more you practice, the more tail wags you get! 🐾',
  '¡Vamos! Let\'s go! Barny is ready when you are! 🏃',
  'Consistency is key — even Barny does the same walk every day! 🐾',
  'In Spanish, a good boy is "un buen chico." Barny is muy buen chico. 🐕',
  '¡Ánimo! You\'ve got this! Barny has never failed a sniff test. 🐾',
  'Small steps every day = big results. Barny learned to sit eventually. 🐕',
  'Fun fact: Barny\'s favourite Spanish word is "queso." It means cheese. 🧀',
  'Barny tip: say the Spanish words OUT LOUD. Woof loudly! 🔊',
  '¡Buenos días! Or if it\'s night — ¡Buenas noches! Barny covers all hours. 🐾',
  'You\'re here, which means you\'re already winning. Fetch! 🎾',
  'Barny\'s dream: visiting Spain. The smell. The food. The perros. 🇪🇸',
  '¡Excelente! You just thought about learning Spanish. First step done! 🐾',
  'In Spanish, "amigo" means friend. Barny is your amigo. 🐕',
  'Barny has been known to bork in both English AND Spanish. Bilingual king. 🐾',
  'If Barny can learn "sit," "stay," and "fetch," you can learn Spanish. ¡Fácil! 🐕',
  '"La vida es bella" — life is beautiful! Especially with Barny in it. 🐾',
  'Barny\'s studying too. He\'s on lesson one of "stop eating shoes." 🐕',
  '¿Cómo estás? That means "how are you?" Barny hopes you\'re doing great! 🐾',
  'Mistakes are just treats on the path to fluency. Nom nom. 🦴',
  'Barny rating: this study session will be a solid 10/10 wags. 🐾',
  '"Mañana" means tomorrow — but don\'t put studying off until mañana! 🐕',
  'Did someone say "vocabulario"? That\'s Barny\'s FAVOURITE word. 🐾',
  'Every correct answer makes Barny do a little spin. Get spinning! 🌀',
  'Barny fact: "cachorro" means puppy. Barny is eternally a cachorro at heart. 🐕',
  'You could be watching TV right now. But you\'re HERE. Legend. 🐾',
  '"Gracias" means thank you! Barny says gracias for studying today. 🐕',
  'Barny once barked in Spanish. It sounded like "guau." Absolutely nailed it. 🐾',
  'The secret to learning a language: repetition, repetition, repetición. 🦴',
  '"Bonito" means pretty. Like Barny\'s fur. Just saying. 🐕',
  '¡Mucho gusto! Nice to meet you — or nice to see you again! 🐾',
  'Barny tip: attach Spanish words to smells. Dog brain technique. 🐕',
  '"Tranquilo" means calm. Barny is the OPPOSITE of tranquilo. 🐾',
  'You are doing amazing sweetie. Barny said so. 🐕',
  '"Hoy" means today. TODAY is a great day to learn something new! 🐾',
  'Fun fact: there are 21 Spanish-speaking countries. That\'s 21x the sniffs! 🐕',
  'Barny\'s vocabulary is: woof, bark, bork, guau. He\'s working on it. 🐾',
  '"Lluvia" means rain. Barny hates it. But he loves that you\'re studying! 🐕',
  'Ole! Ole! Barny does not know what that means but he feels it deeply. 🐾',
  '"Fuerte" means strong. You are very fuerte for doing this. 🐕',
  'Barny\'s longest tail wag record: 4 minutes straight. Beat it with a streak! 🐾',
  '"Siempre" means always. Barny will ALWAYS be cheering you on. 🐕',
  '"Sueño" means dream OR sleep. Barny is living his sueño right now. 🐾',
  'Achievement unlocked: opened the app. Barny is proud. 🐕',
  '"Corazón" means heart. Barny has a very big corazón for learning humans. 🐾',

  // 200 more
  'Barny tried to order food in Spain once. He said "guau." They understood. 🐕',
  '"Feliz" means happy. Barny is VERY feliz right now. 🐾',
  'One word a day keeps the forgetting away. Barny heard that somewhere. 🦴',
  '¡Perfecto! Barny gives that a 12 out of 10 paws. 🐾',
  '"Dormir" means to sleep. Barny is an expert. PhD level. 🐕',
  'Barny once stared at a Spanish textbook for 20 minutes. Basically fluent. 🐾',
  '"Correr" means to run. Barny does this whenever he hears the word "bath." 🏃',
  'You are braver than you believe and smarter than Barny, which is saying something. 🐕',
  '"Agua" means water. Barny knocks his bowl over daily. Very refreshing. 🐾',
  'Barny\'s spirit animal is himself, but Spanish. 🇪🇸',
  '"Jugar" means to play. Barny endorses this activity 100%. 🎾',
  'If you get one wrong, that\'s fine. Barny fails to catch balls constantly. 🐕',
  '"Noche" means night. Barny is afraid of the dark. Don\'t tell anyone. 🌙',
  'The Spanish word for tail is "cola." Barny wags his cola at you. 🐾',
  '"Rápido" means fast. Barny can go rápido when there are squirrels involved. 🐕',
  'Every great linguist started knowing zero words. Barny started knowing zero words too. 🐾',
  '"Hambre" means hunger. This is Barny\'s permanent state. 🦴',
  'Barny would write flashcards but he has no thumbs. He relies on YOU. 🐕',
  '"Sol" means sun. Barny loves lying in the sun. Very important vocabulary. 🌞',
  '¡Increíble! That means incredible. Which is what you are. 🐾',
  '"Pelota" means ball. The most important word in any language. 🎾',
  'Barny once dreamed in Spanish. He woke up confused but impressed. 🐕',
  '"Listo" means ready OR clever. Barny hopes you are both. 🐾',
  'The hardest part of learning Spanish is starting. You already did that. Go Barny! 🦴',
  '"Pasear" means to go for a walk. Barny perked up just reading that. 🐕',
  'Barny trivia: "perrito caliente" is a hot dog. Barny is conflicted about this. 🌭',
  '"Jardín" means garden. Where Barny buries his vocabulary notes. 🐾',
  'Did you stretch before this study session? Barny always stretches. Look at him go. 🐕',
  '"Lluvia" means rain. Barny\'s nemesis. He will not be taking questions. 🌧️',
  'Barny has a 5-star Duolingo review in his head. He just can\'t type it. 🐾',
  '"Cama" means bed. Barny is thinking about his cama right now. 🛏️',
  'Proud of you! Barny does a bork of celebration in your honour. 🐕',
  '"Ventana" means window. Where Barny watches the world and judges it. 🐾',
  'You\'ve learned more Spanish than most people will this week. Barny verified. 🦴',
  '"Hueso" means bone. Barny just got very excited. Please continue. 🐕',
  'Barny believes language learning is a marathon, not a sprint. But also a sprint. Also fetch. 🐾',
  '"Caminar" means to walk. Barny\'s second favourite activity after eating. 🐕',
  'Barny tip: pretend you\'re a dog. Dogs learn through repetition and rewards. It works. 🐾',
  '"Abrir" means to open. Like opening your mind to Spanish! Barny is very wise. 🦴',
  'In Spain, dogs say "guau." In Mexico too. Barny is internationally relevant. 🐕',
  '"Frío" means cold. Barny shivers dramatically to illustrate. 🐾',
  'Your brain is like a sponge right now. Barny has eaten a sponge before. Different. 🐕',
  '"Calor" means heat. Barny pants enthusiastically to demonstrate. 🐾',
  'Barny thinks Spanish accents are very cool. The tildes! The upside-down marks! ¡Woof! 🦴',
  '"Juguete" means toy. Barny has opinions about which ones are best. Many opinions. 🐕',
  'Word of wisdom from Barny: if you don\'t know a word, just say "cosa." It means "thing." 🐾',
  '"Correa" means leash. Barny respects the leash. (He does not respect the leash.) 🐕',
  'Every word you learn lives rent-free in your brain. Make it a nice neighbourhood. 🐾',
  '"Fuera" means outside. Barny just sprinted to the door. 🦴',
  'Barny\'s favourite Spanish sentence: "¿Dónde está mi pelota?" Where is my ball? 🐕',
  '"Bonito" means pretty and "lindo" means cute. Barny is ambos. 🐾',
  'The trick to Spanish is confidence. Say it loud! Like a bork! BORK! 🐕',
  '"Descansar" means to rest. Barny is very qualified to teach this one. 🐾',
  'Fun fact: "can" in Spanish means "dog." Old Spanish. Barny finds this deeply meaningful. 🦴',
  '"Escuchar" means to listen. Barny\'s ears perk up at the word "walk." Expert listener. 🐕',
  'Barny considered a career in translation but couldn\'t figure out the keyboard. Here he is. 🐾',
  '"Ruidoso" means noisy. Also an accurate description of Barny at 6am. 🐕',
  '"Suave" means soft OR smooth. Barny\'s fur is muy suave, thank you. 🐾',
  '"Esperar" means to wait OR to hope. Barny waits AND hopes for treats simultaneously. 🦴',
  'Every mistake you make is data. Barny has a LOT of data about holes in gardens. 🐕',
  '"Tranquilo/a" means calm. Barny hears this a lot. Working on it. 🐾',
  '"Encantado/a" means delighted to meet you! Barny is always encantado. 🐕',
  'Barny philosophy: treat every wrong answer like a squirrel — chase it down next time. 🐾',
  '"Nuevo" means new. A new session, a new chance, a new Barny (same Barny). 🦴',
  '"Viejo" means old. Barny refuses to apply this word to himself. Eternally young. 🐕',
  '"Siesta" is the same in Spanish! A nap. Barny is a siesta professional. 🐾',
  'Barny once sat perfectly still for 3 minutes. Peak discipline. You can do this. 🐕',
  '"Hablar" means to talk. Barny talks (barks) constantly. He gets it. 🐾',
  '"Leer" means to read. Barny licks pages. Close enough. 🦴',
  '"Escribir" means to write. Barny paws at the screen. Very close. 🐕',
  '"Aprender" means to learn. This is literally what you\'re doing. Barny is THRILLED. 🐾',
  'The Spanish word "madrugada" means the hours between midnight and dawn. Very poetic. Very Barny. 🌙',
  '"Tarde" means afternoon OR late. Barny is never late. He arrives exactly when treats appear. 🐕',
  '"Temprano" means early. Barny is always temprano for breakfast. Always. 🐾',
  '"Semana" means week. Seven days. Seven chances to impress Barny. 🦴',
  '"Mes" means month. Barny marks months by how many walks he\'s had. A lot. 🐕',
  '"Año" means year. Barny is doing his best regardless of the year. 🐾',
  'Remember: "por favor" means please. Barny says it with his eyes constantly. 🐕',
  '"De nada" means you\'re welcome! Barny accepts your gratitude with a wag. 🐾',
  '"Lo siento" means I\'m sorry. Barny says this to the bins he knocks over. 🦴',
  '"No entiendo" means I don\'t understand. Barny says this to the bath. Every time. 🐕',
  '"¡Qué bueno!" means how great! Barny says this whenever food appears. 🐾',
  '"Despacio" means slowly. Barny eats the opposite of despacio. 🦴',
  'Barny once met a dog from Madrid. They got on great. Mostly sniffing. 🐕',
  '"Encontrar" means to find. Barny is excellent at finding smells. Transferable skill. 🐾',
  '"Perder" means to lose. Barny loses his ball daily and is fine. Resilience. 🐕',
  '"Ganar" means to win. Today you are GANAR-ing. Barny confirms. 🐾',
  '"Intentar" means to try. The fact that you\'re here means you\'re already intentando. 🦴',
  '"Olvidar" means to forget. Barny forgot where he buried his bone. Still searching. 🐕',
  '"Recordar" means to remember. This app is literally for that! Barny is very relevant! 🐾',
  '"Preguntar" means to ask. Barny asks for treats with his entire face. Works every time. 🦴',
  '"Contestar" means to answer. Barny always answers. The answer is usually "woof." 🐕',
  '"Entender" means to understand. Barny understands "walk," "treat," and "no" (he ignores no). 🐾',
  '"Empezar" means to begin. You already empezaste. Look at you go! 🐕',
  '"Terminar" means to finish. Barny finishes his food in 4 seconds flat. 🐾',
  'Barny tip: translate your thoughts into Spanish while on a walk. Barny does this. 🦴',
  '"Pensar" means to think. Barny is thinking about you right now. Proud thoughts. 🐕',
  '"Saber" means to know. Barny knows one thing: you are doing amazing. 🐾',
  '"Poder" means to be able to / can. YOU PODER THIS. Barny is sure. 🐕',
  '"Querer" means to want OR to love. Barny quieres treats AND you. Equally. 🐾',
  '"Tener" means to have. Barny has: one ball, one bed, and limitless love for Spanish learners. 🦴',
  '"Ir" means to go. ¡Vamos! Let\'s go! Barny is already at the door. 🐕',
  '"Venir" means to come. Barny always comes when called. (This is a lie.) 🐾',
  '"Poner" means to put. Barny puts things in his mouth. Educational. 🦴',
  '"Hacer" means to do or make. What are you going to hacer today? Barny votes: Spanish! 🐕',
  '"Ver" means to see. Barny sees a lot from the window. Mainly squirrels. 🐾',
  '"Dar" means to give. Please give Barny a treat. It\'s for motivation purposes. 🦴',
  'Barny once tried yoga. "Downward dog" felt very natural. 🐕',
  '"Saltar" means to jump. Barny jumps for: joy, food, and no reason at all. 🐾',
  '"Nadar" means to swim. Barny is... uncertain about swimming. The jury is out. 🐕',
  '"Cavar" means to dig. Barny is a cavar champion. Gold medal. 🐾',
  '"Olfatear" means to sniff. Barny\'s greatest talent. 10/10 technique, judges say. 🦴',
  'Barny has 300 million scent receptors. He is using them all to sense your progress. 🐕',
  '"Ladrar" means to bark. Barny does this. All the time. About everything. 🐾',
  '"Morder" means to bite. Barny ONLY does this to toys. Mostly. 🦴',
  '"Crecer" means to grow. Your Spanish is growing! Barny measured. 🐕',
  '"Cambiar" means to change. Every session changes your brain. Science! Barny! 🐾',
  '"Ayudar" means to help. Barny helps by existing. Very effective. 🦴',
  '"Llevar" means to carry or wear. Barny carries the weight of your motivation. 🐕',
  '"Traer" means to bring. Barny brings vibes. Good vibes. 🐾',
  '"Buscar" means to search or look for. Like how Barny looks for squirrels: obsessively. 🦴',
  '"Comprar" means to buy. Barny would buy treats. If he had money. Hint hint. 🐕',
  '"Comer" means to eat. Barny\'s primary skill. Expert level. Unbeatable. 🐾',
  '"Beber" means to drink. Barny drinks, then puts his wet beard on you. You\'re welcome. 🦴',
  'Your streak is like Barny\'s tail — keep it going! 🐕',
  '"Dormir" means to sleep. Barny maintains 16 hours per day. Aspirational. 🐾',
  '"Soñar" means to dream. Barny dreams about squirrels AND your Spanish success. 🦴',
  'Barny once went to a fiesta. He ate everything on the table. Legend. 🐕',
  '"Bailar" means to dance. Barny\'s tail is basically dancing right now. 🐾',
  '"Cantar" means to sing. Barny howls along to music. Artistic interpretation. 🦴',
  '"Esconder" means to hide. Where Barny goes when he hears the word "bath." 🐕',
  '"Compartir" means to share. Barny believes in sharing... mostly. 🐾',
  '"Necesitar" means to need. Barny needs: food, walks, and for you to succeed. 🦴',
  '"Deber" means to owe or should. You should (deber) learn a word today. Barny is firm. 🐕',
  '"Preferir" means to prefer. Barny prefers sunny walks and correct flashcard answers. 🐾',
  '"Parecer" means to seem or appear. It seems like you\'re doing great! Barny concurs. 🦴',
  '"Creer" means to believe. Barny believes in you more than he believes in the bath. 🐕',
  '"Sentir" means to feel. Barny feels everything very intensely. It\'s a gift. 🐾',
  '"Vivir" means to live. ¡Vive el español! Live the Spanish! Barny commands it. 🦴',
  '"Trabajar" means to work. Learning IS work! Hard, rewarding work. Barny respects it. 🐕',
  '"Descansar" means to rest. After this session: rest. You earned it. So did Barny. 🐾',
  '"Disfrutar" means to enjoy. ¡Disfruta tu sesión! Enjoy your session! 🦴',
  'Barny\'s top tip: visualise the word. Picture a perro when you say perro. (Picture Barny.) 🐕',
  '"Emocionado/a" means excited. Barny is emocionado EVERY single morning. Non-negotiable. 🐾',
  '"Nervioso/a" means nervous. It\'s okay to feel nervioso. Barny feels it before baths. 🦴',
  '"Cansado/a" means tired. It\'s okay to be cansado. Rest, then come back. Barny will wait. 🐕',
  '"Aburrido/a" means bored. You\'re NOT aburrido — you\'re here! With Barny! 🐾',
  '"Orgulloso/a" means proud. Barny is muy orgulloso of you. Always. 🦴',
  '"Asustado/a" means scared. Don\'t be asustado of hard words. Attack them like squirrels. 🐕',
  '"Confundido/a" means confused. It\'s okay. Even Barny gets confundido by the leash. 🐾',
  '"Sorprendido/a" means surprised. Barny gets surprised by his own reflection daily. 🦴',
  '"Tranquilo/a" means calm. Breathe. Take your time. Barny is in no rush. Well. Maybe a little. 🐕',
  '"Seguro/a" means sure OR safe. Barny makes you feel seguro. It\'s his job. 🐾',
  '"Listo/a" means ready. Are you listo? Barny has been listo since 6am. 🦴',
  '"Nuevo/a" means new. New vocabulary incoming! Barny is on the edge of his bed. 🐕',
  '"Simpático/a" means friendly. That\'s Barny. The most simpático dog in the game. 🐾',
  '"Inteligente" means intelligent. Barny believes this describes you exactly. 🦴',
  '"Valiente" means brave. You are valiente for learning something new. Barny salutes. 🐕',
  '"Paciente" means patient. Barny is patient. For about 10 seconds. Then he barks. 🐾',
  '"Curioso/a" means curious. Curiosity is how you learn. Sniff everything! 🦴',
  'Barny once confused "rojo" (red) and "ojo" (eye). He looked at things differently after. 🐕',
  '"Verde" means green. Barny rolls in green things. Not all of them pleasant. 🐾',
  '"Azul" means blue. The colour of the sky Barny stares at during walks. 🦴',
  '"Amarillo" means yellow. Barny has a yellow ball. It is his most prized possession. 🐕',
  '"Naranja" means orange (the colour AND the fruit). Barny is fascinated by oranges. 🐾',
  '"Blanco" means white. Barny has white paws (when they\'re clean, which is rarely). 🦴',
  '"Negro" means black. Barny\'s nose is negro. Perfect and important. 🐕',
  '"Gris" means grey. What Barny\'s muzzle is slowly becoming. Distinguished. 🐾',
  '"Grande" means big. Barny\'s energy is grande. Always. 🦴',
  '"Pequeño/a" means small. Barny was pequeño once. Very briefly. 🐕',
  '"Alto/a" means tall or high. Barny jumps alto for treats. Very alto. 🐾',
  '"Bajo/a" means short or low. Barny goes bajo when he wants belly rubs. 🦴',
  '"Largo/a" means long. Like the long list of words you\'re going to learn! 🐕',
  '"Corto/a" means short. This quip is corto. Unlike Barny\'s love for you. 🐾',
  '"Fácil" means easy. Some words ARE fácil. Celebrate those! 🦴',
  '"Difícil" means difficult. Some words are difícil. Still worth it. Barny struggled with "stay." 🐕',
  '"Importante" means important. Spanish is importante. Barny is importante. Both true. 🐾',
  '"Interesante" means interesting. Barny finds everything interesting. Sticks. Smells. You. 🦴',
  '"Divertido/a" means fun. Learning Spanish IS divertido. Barny insists. 🐕',
  '"Delicioso/a" means delicious. Barny considers most things delicioso. Including socks. 🐾',
  '"Increíble" means incredible. Your progress is increíble. Barny checked the data. 🦴',
  '"Perfecto/a" means perfect. No one is perfect — but you\'re perfectísimo to Barny. 🐕',
  '"Especial" means special. You are very especial. Barny has known since the start. 🐾',
  '"Famoso/a" means famous. One day you\'ll be famoso for your Spanish. Barny will say he knew you. 🦴',
  '"Favorito/a" means favourite. YOU are Barny\'s favourite. Don\'t tell the others. 🐕',
  '"Normal" is the same in Spanish! See, you already knew one! 🐾',
  '"Hospital" is the same too! Spanish has loads of English cognates. Sneaky easy! 🦴',
  '"Animal" is exactly the same in Spanish. Barny approves of this word. 🐕',
  '"Chocolate" is almost the same — "chocolate." Essential vocabulary, says Barny. 🐾',
  '"Hotel" is the same in Spanish. Barny has never stayed in one. Yet. 🦴',
  '"Universal" is the same in Spanish. See the pattern? "-al" words often cross over! 🐕',
  '"Natural" is the same in Spanish too! You\'re building vocab without even trying! 🐾',
  '"Tropical" — same in Spanish! Barny would like to visit somewhere tropical. 🦴',
  '"Central" — same in Spanish. You are central to Barny\'s daily motivation. 🐕',
  '"Actual" means CURRENT in Spanish, not real. Barny learned this the hard way. 🐾',
  'False friend alert: "embarazada" means pregnant, NOT embarrassed. Barny saves you. 🦴',
  'False friend: "sensible" in Spanish means sensitive, not sensible. Barny is both. 🐕',
  '"Éxito" means success, NOT exit. Your éxito in Spanish is Barny\'s whole goal. 🐾',
  '"Realizar" means to achieve or carry out, not to realise. Barny realised this recently. 🦴',
  'The verb "molestar" means to bother or annoy. Barny does not molestar. (He does.) 🐕',
  'Barny says: don\'t just memorise — USE the words. Talk to yourself. Talk to Barny! 🐾',
  'Write Spanish words on sticky notes. Put them everywhere. Like Barny puts muddy paws. 🦴',
  'Label things in your house in Spanish. Your bed is "la cama." Barny\'s is too. 🐕',
  'Change your phone language to Spanish for a week. Barny dares you. 🐾',
  'Listen to Spanish music! Barny recommends anything with a good beat for zoomies. 🦴',
  'Watch a show with Spanish subtitles. Barny watches from the sofa. Prime position. 🐕',
  'The more you immerse, the faster you learn. Barny immersed himself in a puddle once. 🐾',
  'Reading in Spanish, even slowly, rewires your brain. Barny\'s brain is very rewired. 🦴',
  'Think of a Spanish word right now. That\'s one more than you knew before Barny. 🐕',
  'Barny\'s final wisdom: show up. Every day. Even for five minutes. It all adds up. 🐾',
  '"¡Hasta luego!" — see you later! Barny will be here. Waiting. Always waiting. 🦴',

  // more — same voice: varied structure, Barny-led, callbacks to the lore
  '"Ardilla" means squirrel. Barny\'s lifelong nemesis finally has a name. ¡ARDILLA! 🐿️',
  '"Gato" means cat. Barny has... complicated feelings. Let\'s move on. 🐕',
  '"Pájaro" means bird. Barny watches pájaros for hours. It\'s basically television. 🐦',
  '"Vaca" means cow. Barny met one once. He has never fully recovered. 🐄',
  '"Caballo" means horse. Barny is convinced it\'s just a very large, confusing dog. 🐴',
  '"Cero" means zero. The number of squirrels Barny has ever caught. He stays hopeful. 🐿️',
  '"Pata" means paw. "Patata" means potato. One letter apart — Barny finds this dangerous. 🥔',
  '"Oreja" means ear. Barny\'s orejas detect the fridge opening from three rooms away. 🐕',
  '"Lengua" means tongue AND language. Barny only uses his for one of those. 🐾',
  '"Barriga" means belly. Scientifically the most important part of Barny, for rubbing. 🦴',
  '"Diente" means tooth. Barny uses his dientes mostly on socks. We\'re working on it. 🐕',
  '"Nariz" means nose. Barny\'s is always wet, always working, always judging. 🐾',
  '"Viento" means wind. Barny\'s ears become two majestic flags in the viento. 🐕',
  '"Nieve" means snow. Barny becomes a puppy again the second he sees nieve. ❄️',
  '"Tormenta" means storm. Barny supervises every tormenta from under the bed. ⛈️',
  '"Nube" means cloud. Barny naps measurably better under a good nube. 🐾',
  '"Casa" means house. "Mi casa es tu casa" — Barny means it. Especially the sofa. 🏠',
  '"Calle" means street. Where Barny conducts his very important sniffing research. 🐕',
  '"Parque" means park. Say "parque" near Barny and witness what happens. 🐾',
  '"Playa" means beach. Barny on a playa is pure, uncut chaos and joy. 🏖️',
  '"Montaña" means mountain. Barny would climb one for a stick. He has his priorities. ⛰️',
  '"Mar" means sea. Barny barked at the mar once. The mar did not respond. 🌊',
  '"Tienda" means shop. Barny waits outside looking tragic, for maximum sympathy. 🐕',
  '"Zapato" means shoe. Barny has a long, complicated history with zapatos. RIP. 👟',
  '"Calcetín" means sock. Barny\'s greatest temptation. His Everest. 🧦',
  '"Sombrero" means hat. Barny wore one for a photo once. He has forgiven no one. 🎩',
  '"Abrazar" means to hug. Barny gives full-body abrazos. Whether you asked or not. 🤗',
  '"Llorar" means to cry. Barny llora a tiny bit when you leave. Then he naps. 🐾',
  '"Gritar" means to shout. Barny prefers it. It\'s really just loud borking. 🔊',
  '"Llegar" means to arrive. You llegaste! You arrived! That\'s the hardest part done. 🦴',
  '"Quedarse" means to stay. The one command Barny genuinely mastered. Eventually. 🐕',
  '"Salud!" means cheers — or bless you after a sneeze. Barny sneezes purely for attention. 🐾',
  '"Claro" means "of course" (literally "clear"). Of course you can do this. ¡Claro! 🦴',
  '"Vale" means okay in Spain. Barny says vale to everything. Easygoing king. 🐕',
  '"Genial" means great. This session? Genial. Barny called it in advance. 🐾',
  '"¿Qué tal?" means how\'s it going? Going great — now that you\'re here. Barny\'s words. 🐕',
  'False friend: "ropa" means clothes, NOT rope. Barny finds this genuinely upsetting. 🧦',
  'False friend: "pie" means FOOT, not the dessert. Barny was so, so disappointed. 🥧',
  'False friend: "carpeta" means folder, not carpet. Barny was misled for years. 🐕',
  'Cognate hack: "-tion" usually becomes "-ción." Nación, estación, información. Free words! 🦴',
  'Barny doesn\'t care if you got them all wrong. He cares that you showed up. 🐾',
  'You came back. Barny knew you would. He never doubted you. Not once. 🐕',
  'Tough day? Do ONE word. That\'s the whole goal. Barny will be thrilled. Go. 🦴',
  'Barny\'s ranking of good things: 1. Treats. 2. You, studying. 3. Treats again. 🦴',
  'Barny\'s not saying you\'re his favourite human. But you\'re his favourite human. 🐾',
  'The Spanish you learn today, you\'ll still have in ten years. Barny is a little jealous. 🐕',
  'Somewhere there\'s a future you who speaks Spanish fluently. Barny waves at them. 🌟',
  'Barny can\'t read a word of this app. He just watches you smile at it. Enough for him. 🐾',

  // more — animals, food, house, transport, connectors, and pure hype
  '"Oso" means bear. Barny saw one on TV and barked for his honour. Brave boy. 🐻',
  '"Conejo" means rabbit. Fast, fluffy, and personally offensive to Barny. 🐰',
  '"Pato" means duck. Barny respects the pato. They share a deep fondness for puddles. 🦆',
  '"Pez" means a living fish; "pescado" is the kind you eat. Barny is fascinated by both. 🐟',
  '"Mariposa" means butterfly. Barny chases them and catches nothing. Pure joy regardless. 🦋',
  '"Cerdo" means pig — and also a messy person. Barny qualifies on both counts. 🐷',
  '"Rana" means frog. Barny poked one once. It hopped. He still has questions. 🐸',
  '"Cabeza" means head. Barny tilts his cabeza at hard words too. Solidarity. 🐕',
  '"Mano" means hand. Barny has no manos — just paws and pure determination. 🐾',
  '"Pelo" means hair or fur. Barny sheds his pelo on everything you own. A gift, really. 🐕',
  '"Baño" means bathroom AND bath. Barny\'s feelings on this word are deeply mixed. 🛁',
  '"Cocina" means kitchen. Barny\'s favourite room. The sacred treat dimension. 🍳',
  '"Puerta" means door. Barny stands hopefully by the puerta roughly 400 times a day. 🚪',
  '"Suelo" means floor. Where Barny dramatically flops the instant he\'s ignored. 🐕',
  '"Jamón" means ham. Barny would memorise the entire dictionary for one slice. 🍖',
  '"Miel" means honey. Sweet — like the fact you came back today. Barny noticed. 🍯',
  '"Sal" means salt. Barny licked some once. Strong reaction. Zero regrets. 🧂',
  '"Vino" means wine. Not for dogs. Barny supervises responsibly from the floor. 🍷',
  '"Coche" means car. Head out the window, ears flapping — Barny\'s idea of heaven. 🚗',
  '"Bici" is short for bicycle. Barny chases them. For sport. For honour. 🚲',
  '"Cazar" means to hunt. Barny\'s success rate is zero. His commitment is total. 🐿️',
  '"Perseguir" means to chase. Barny\'s entire personality in a single verb. 🐕',
  '"Lamer" means to lick. Barny\'s preferred way of greeting, thanking, and simply existing. 🐾',
  '"Masticar" means to chew. Barny\'s second language, after barking. 🦴',
  '"Enterrar" means to bury. Barny hides treasures everywhere and forgets all of them. 🐕',
  '"Romper" means to break. Barny did not break the vase. (Barny broke the vase.) 🐾',
  '"Seguir" means to follow OR to continue. Barny follows you room to room. ¡Sigue así! 🐕',
  '"Limpiar" means to clean. Barny "helps" by licking the plates first. 🍽️',
  '"Sucio" means dirty. Barny\'s natural, preferred, and frankly default state. 🐾',
  '"Mojado" means wet. Barny + rain + one shake = everyone is mojado now. 💦',
  '"Peludo" means furry. Barny is extremely peludo and outrageously proud of it. 🐕',
  '"Lleno" means full. Barny is never lleno. There\'s always room. Science is baffled. 🦴',
  '"Dulce" means sweet. Like you, for showing up again. Barny said it, not me. 🍬',
  '"Pero" means but. Barny knows "no walk yet, PERO soon." Devastated but hopeful. 🐾',
  '"Porque" means because. Why study? Porque future-you will high-five you. Barny promises. 🐕',
  '"También" means also. Barny loves you. Barny también loves treats. Both very real. 🦴',
  '"Ojalá" means hopefully — it\'s from Arabic for "God willing." Barny finds it beautiful. ✨',
  '"Menos mal" means thank goodness. Menos mal you opened the app today. Barny exhaled. 🐾',
  '"Por supuesto" means of course. Can you do this? Por supuesto. Barny never doubted it. 🐕',
  '"Buen provecho" means enjoy your meal. Barny says it to himself before inhaling dinner. 🍽️',
  '"¿Por qué?" means why? Barny asks why baths exist. To this day, no one has answered. 🛁',
  '"Nunca" means never. Barny will nunca stop believing in you. NUNCA. 🐾',
  '"Todavía" means still or yet. Can\'t say it yet? Just add "todavía." You can\'t say it YET. 🐕',
  'Barny is doing zoomies right now. The cause? You. Opening this app. That\'s it. 🐕',
  'Progress isn\'t loud. It\'s one quiet word at a time. Barny sees every single one. 🐾',
  'Nobody is born knowing Spanish. Or knowing "sit." Barny and you: same journey. 🦴',
  'Barny would give you a gold star, but — no thumbs. Picture it. It\'s very shiny. ⭐',
  'Future-you is fluent and grateful. Present-you is doing the work. Barny loves you both. 🐕',

  // more — family, jobs, time, weather, and Spain-flavoured phrases
  '"Familia" means family. You\'re part of Barny\'s familia now. No take-backs. 🐾',
  '"Madre" means mother. "¡Madre mía!" is exactly what Barny thinks when the doorbell rings. 🐕',
  '"Hermano" means brother. Barny considers every dog he meets an instant hermano. 🐾',
  '"Bebé" means baby. Barny was a bebé once. Tiny. Adorable. A complete menace. 🐶',
  '"Abuela" means grandmother. Abuelas give the best secret snacks. Barny knows this globally. 🦴',
  '"Cartero" means postman. Barny has a complicated professional relationship with the cartero. 📬',
  '"Veterinario" means vet. Barny respects the veterinario — from a safe, trembling distance. 🐕',
  '"Profesor" means teacher. Barny is YOUR profesor now. Sole qualification: enthusiasm. 🎓',
  '"Médico" means doctor — basically "medic." Another sneaky cognate. Barny cracked it. 💊',
  '"Bombero" means firefighter. Barny would be a useless bombero but a deeply loyal mascot. 🚒',
  '"Tiempo" means both time AND weather. One word, two jobs. Barny is impressed. ⏰',
  '"Cumpleaños" means birthday. Barny celebrates his with cake he is not technically allowed. 🎂',
  '"Reloj" means clock or watch. Barny\'s internal reloj is permanently set to "dinner soon?" 🕐',
  '"¿Qué hora es?" means what time is it? (It\'s treat o\'clock. It is always treat o\'clock.) 🕐',
  '"Fin de semana" means weekend. Two bonus days of walks. Barny lives for it. 🗓️',
  '"¿Quién?" means who? "¿Quién es un buen chico?" Barny already knows. It\'s him. 🐕',
  '"¿Cuánto?" means how much or how many. Barny\'s answer, regarding treats, is always "más." 🦴',
  '"Arcoíris" means rainbow. Barny can\'t see every colour, but he believes in it for you. 🌈',
  '"Niebla" means fog. Barny vanishes into the niebla and reappears looking smug. 🌫️',
  '"Trueno" means thunder. Barny\'s sworn enemy. He barks back valiantly every time. ⛈️',
  '"Marrón" means brown. Barny is mostly marrón. A distinguished, frequently muddy marrón. 🐕',
  '"Rosa" means pink AND rose. Barny sniffed a rosa once and sneezed for a full minute. 🌹',
  '"Viajar" means to travel. Learn Spanish and the whole map opens up. Barny packs a stick. 🗺️',
  '"Cocinar" means to cook. Barny "supervises" all cooking from directly underfoot. 🍳',
  '"Repetir" means to repeat. The secret sauce of learning. Repite, repite, repite. Barny chants. 🔁',
  '"Respirar" means to breathe. Stuck on a word? Respira. Then try again. Barny breathes with you. 🌬️',
  '"Conocer" means to know a person or place — "saber" is for facts. Two verbs, one English word! 🤝',
  '"Mejorar" means to improve. Every session, you mejoras. Barny keeps graphs. (He doesn\'t. Still.) 📈',
  '"Elegir" means to choose. You chose to be here today. Barny elige you right back. 🐾',
  '"Prometer" means to promise. Barny promises this gets easier. He even pinky-promises. (No pinkies.) 🐕',
  '"Pagar" means to pay. Barny would pay in tail wags if any shop accepted them. 🦴',
  '"Guapo" means handsome. Barny is, objectively and scientifically, muy guapo. 🐕',
  '"Loco" means crazy. Barny goes a little loco at 8pm sharp. The zoomies are non-negotiable. 🌀',
  '"Amable" means kind. Be amable to yourself when you slip up. Barny insists on it. 🐾',
  '"Libre" means free. Weekends, open fields, a Barny off the leash — all gloriously libre. 🐕',
  '"Vacío" means empty. Like Barny\'s food bowl: perpetually and tragically vacío. 🦴',
  '"No pasa nada" means it\'s no big deal. Got one wrong? No pasa nada. Barny\'s seen worse. 🐾',
  '"Poco a poco" means little by little. That is exactly how fluency gets built. Poco a poco. 🐕',
  '"¡Qué rico!" means how delicious! Barny says it about dinner, socks, AND the bin. 🍖',
  '"¡Cuidado!" means careful! / watch out! Barny shouts it at the vacuum daily. ⚠️',
  '"Más o menos" means more or less. How fluent is Barny? Más o menos. Mostly menos. 🐾',
  '"Venga" means come on! (in Spain). Venga, one more word! Barny is fully rooting for you. 🐕',
  'Some days the words stick, some days they don\'t. You showed up anyway. Barny bows. 🐾',
  'Barny measures your progress in tail wags. The graph is going straight up. 📈',
  'You\'re not behind. There is no behind. There\'s just you and the next word. Barny\'s sure. 🐕',
  'The hardest rep is opening the app. You already did it. Barny is positively beaming. 🦴',
  'Ten words from now you won\'t recall this moment — but your brain keeps them. Barny\'s magic. ✨',
]

const ALL_DOGS = [dog1, dog2, dog3, dog4, dog5, dog6, dog7, dog8, dog10, dog11, dog12]

export function RotatingBarnyIcon({ size = 18 }: { size?: number }) {
  const [idx, setIdx] = useState(0)
  useEffect(() => {
    const id = setInterval(() => setIdx((i) => (i + 1) % ALL_DOGS.length), 100000)
    return () => clearInterval(id)
  }, [])
  return (
    <img
      src={ALL_DOGS[idx]}
      alt="Barny"
      style={{ width: size, height: size, objectFit: 'contain', display: 'inline-block', verticalAlign: 'middle', transform: 'scaleX(-1)' }}
    />
  )
}

export function Barny({ message, size = 'medium', pose, wordIdx = -1 }: BarnyProps) {
  const [randomSrc] = useState(() => FRIENDLY_DOGS[Math.floor(Math.random() * FRIENDLY_DOGS.length)])
  const [resolvedMessage] = useState(() => message ?? RANDOM_QUIPS[Math.floor(Math.random() * RANDOM_QUIPS.length)])
  const src = pose ? POSE_DOG[pose] : randomSrc
  const px = SIZE_PX[size]
  const cropH = Math.round(px * 0.8) // clip the baked-in sprite label at the bottom
  const bubbleFontSize = size === 'small' ? '12px' : '14px'
  const bubbleMaxWidth = size === 'large' ? '200px' : '160px'

  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: '12px', justifyContent: 'center' }}>
      <div style={{ width: px, height: cropH, flexShrink: 0, overflow: 'hidden' }}>
        <img
          src={src}
          alt="Barny the dog"
          width={px}
          style={{ width: px, height: 'auto', display: 'block', transform: 'scaleX(-1)' }}
        />
      </div>

      {resolvedMessage && (
        <div style={{ position: 'relative' }}>
          <div style={{
            position: 'absolute',
            left: '-9px',
            top: '50%',
            transform: 'translateY(-50%)',
            width: 0,
            height: 0,
            borderTop: '7px solid transparent',
            borderBottom: '7px solid transparent',
            borderRight: '9px solid var(--color-window-border)',
          }} />
          <div style={{
            background: 'var(--color-window-bg)',
            border: '2px solid var(--color-window-border)',
            padding: '6px 10px',
            fontSize: bubbleFontSize,
            fontFamily: 'var(--font-ui)',
            maxWidth: bubbleMaxWidth,
            lineHeight: 1.3,
            textAlign: 'left',
            boxShadow: '2px 2px 0 rgba(0,0,0,0.2)',
            borderRadius: '4px',
          }}>
            {wordIdx >= 0
              ? resolvedMessage.split(/\s+/).map((w, i) => (
                  <span key={i} style={{
                    textDecoration: i === wordIdx ? 'underline' : 'none',
                    textDecorationThickness: '2px',
                    transition: 'text-decoration 0.1s',
                  }}>{w}{' '}</span>
                ))
              : resolvedMessage
            }
          </div>
        </div>
      )}
    </div>
  )
}
